protected/controllers/MoviesController.php
<?php

class MoviesController extends Controller
{
	public function actionIndex()
	{
		$movies = Movie::model()->findAll();
		$this->render('index', array('movies'=>$movies));
	}

	public function actionDetail($id=null)
	{
		$this->renderPartial('detail', array(
			'movie'=>$this->loadModel($id), 
			'genres'=>CHtml::listData(Genre::model()->findAll(), 'id', 'name'),
			'countries'=>CHtml::listData(Country::model()->findAll(), 'id', 'name'),
			'directors'=>CHtml::listData(Cast::model()->directorsOnly()->findAll(), 'id', 'name'),
			'actors'=>CHtml::listData(Cast::model()->actorsOnly()->findAll(), 'id', 'name'),
			)
		);
	}

	public function actionList()
	{
		$movies = Movie::model()->findAll();
		$this->renderPartial('list', array('movies'=>$movies));
	}

	public function actionItemList($id)
	{
		$model = $this->loadModel($id);
		$this->renderPartial('item-list', array('movie'=>$model));
	}

	public function actionSave()
	{
		$return = array();
		$id = Yii::app()->request->getParam('id');
		$ajax = Yii::app()->request->getParam('ajax');
		$model = $this->loadModel($id);

		if(isset($_POST['Movie'])) {
			if(!$id)
				$_POST['Movie']['author_id'] = 1;

			if(isset($_POST['action'])) {
				if($_POST['action']=='send-to-approve')
					$_POST['Movie']['status'] = 2;
				else if($_POST['action']=='publish') {
					$_POST['Movie']['status'] = 3;
					$_POST['Movie']['publish_in'] = new CDbExpression('NOW()');
				}
				else if($_POST['action']=='delete')
					$_POST['Movie']['status'] = 0;
			}

			$model->attributes = $_POST['Movie'];

			if($model->validate()) {
				$return['status'] = $model->save();

				// Relations
				MovieCast::model()->checkAndSave($_POST['MovieCast'], $model->id);
				MovieGenre::model()->checkAndSave($_POST['MovieGenre'], $model->id);
				MovieCountry::model()->checkAndSave($_POST['MovieCountry'], $model->id);

				if(isset($_POST['new_file']) AND $_POST['new_file']=='true') {
					$file = new File;
					$fileNames = array(
						'default'		=> 'movie-'.$model->id,
						'medium' 		=> 'movie-'.$model->id.'-medium',
						'small' 		=> 'movie-'.$model->id.'-small',
						'facebook' 		=> 'movie-'.$model->id.'-fb_90x90'
					);
					
					// Move from tmp
					$response = $file->copy(
						array(
							'fileName' => $model->poster,
							'newFileName' => $fileNames['default'],
							'moveFrom' => Yii::app()->params['basePath'] . DS . 'public' . DS . 'movies' . DS,
							'moveTo' => Yii::app()->params['basePath'] . DS . 'public' . DS . 'movies' . DS,
							'removeOriginalFile' => true
						)
					);

					// Update file name
					$fileNames['default'] = $file->fileName;

					if($response) {
						// Generate medium poster
						$file->copy(
							array(
								'fileName' => $fileNames['default'],
								'newFileName' => $fileNames['medium'],
								'moveFrom' => Yii::app()->params['basePath'] . DS . 'public' . DS . 'movies' . DS,
								'moveTo' => Yii::app()->params['basePath'] . DS . 'public' . DS . 'movies' . DS,
								'resizeImageTo' => array('width'=>200, 'height'=>300),
								'removeOriginalFile' => false
							)
						);
						$fileNames['medium'] = $file->fileName;

						// Generate small poster
						$file->copy(
							array(
								'fileName' => $fileNames['default'],
								'newFileName' => $fileNames['small'],
								'moveFrom' => Yii::app()->params['basePath'] . DS . 'public' . DS . 'movies' . DS,
								'moveTo' => Yii::app()->params['basePath'] . DS . 'public' . DS . 'movies' . DS,
								'resizeImageTo' => array('width'=>146, 'height'=>216),
								'removeOriginalFile' => false,
							)
						);
						$fileNames['small'] = $file->fileName;

						// Generate facebook poster (90x90)
						$file->copy(
							array(
								'fileName' => $fileNames['default'],
								'newFileName' => $fileNames['facebook'],
								'moveFrom' => Yii::app()->params['basePath'] . DS . 'public' . DS . 'movies' . DS,
								'moveTo' => Yii::app()->params['basePath'] . DS . 'public' . DS . 'movies' . DS,
								'resizeImageTo' => array('width'=>61, 'height'=>90),
								'removeOriginalFile' => false,
								'watermark' => true,
								'watermark_image' => Yii::app()->params['basePath'] . DS . 'public' . DS . 'images' . DS . 'fb_background_canvas.jpg',
							)
						);
						$fileNames['facebook'] = $file->fileName;

						// Send to Aws S3
						if(Yii::app()->params['aws']['use']) {
							$Aws = new Aws();

							foreach($fileNames as $fn) {
								$st = $Aws->send(Yii::app()->params['basePath'] . DS . 'public' . DS . 'movies' . DS . $fn, $fn);

								if($st)
									@unlink(Yii::app()->params['basePath'] . DS . 'public' . DS . 'movies' . DS . $fn);
							}
						}

						Movie::model()->updateByPk($model->id, array('poster'=>$fileNames['default']));
					}
				}

				$return['info'] = array(
					'id'=>$model->id,
					'url'=>$this->createUrl('/movies/detail/'.$model->id),
					'itemUrl'=>$this->createUrl('/movies/itemlist/'.$model->id),
				);
			}
			else {
				$return['status'] = false;
				$return['info'] = $model->errors;
			}

			if($ajax)
				echo CJavaScript::jsonEncode($return);
			else
				return var_dump($return);
		}
	}

	public function getCast($data)
	{
		$criteria = new CDbCriteria;
		$ids = array();

		foreach($data as $key => $item)
			$criteria->compare('id', $item->cast_id);

		return Cast::model()->findAll($criteria);
	}

	public function loadModel($id)
	{
		$model = Movie::model()->findByPk($id);
		
		if($model===null)
			$model = new Movie;
		
		return $model;
	}

	public function actionUpload()
	{
		$file = new File;
		$response = $file->upload(
				array(
					'requestName' => 'file',
					'moveTo' => Yii::app()->params['basePath'] . DS . 'public' . DS . 'movies' . DS,
					'isImage' => true,
					'extensions' => array('jpg', 'jpeg'),
					'imageMinWidth' => 440,
					'resizeImageTo' => array('width'=>440, 'height'=>660),
					'returnImageContent' => true
				)
			);

		$this->jsonResponse($response);
	}

	public function actionCheckslug()
	{
		$data = Movie::model()->checkSlug(Yii::app()->request->getPost('name'), Yii::app()->request->getPost('id'));
		$this->jsonResponse($data);
	}
}

protected/views/movies/detail.php
<form action="<?php echo $this->createUrl('/movies/save/'.$movie->id) ?>" method="post" name="movieForm" data-post-ajax="true" data-action="">
    <div class="header">
        <h3><?php echo $this->defaultValue($movie, 'name', 'Novo Filme') ?></h3>
        <?php if ($movie->name): ?>
        <p>
            Criado em <span><?php echo $this->dateFormat($movie->register, 'd \'de\' MMMM y \'às\' H:mm') ?></span> <i class="break"></i>
            por <span><?php echo $movie->author ? $movie->author->name : 'Desconhecido' ?></span>
        </p>
        <?php endif ?>

        <div class="buttons">
            <input type="button" class="cancel" value="Cancelar" id="cancel" />
            <input type="button" class="remove submitMovieForm" value="Deletar" id="delete" data-confirm-message="Tem certeza que seja deletar este filme?" />

            <?php if ($movie->name): ?>
                <?php if ($movie->status<=1): ?>
                <input type="button" value="Enviar para aprovação" class="submitMovieForm" id="send-to-approve" data-confirm-message="Tem certeza que deseja enviar para aprovação?" data-confirm-message2="A sinopse foi revisada?" />
                <?php elseif ($movie->status==2): ?>
                <input type="button" value="Publicar" class="submitMovieForm" id="publish" data-confirm-message="Tem certeza que deseja publicar?" />
                <?php endif ?>
            <?php endif ?>
            
            <input type="button" value="Salvar" class="submitMovieForm"/>
        </div>
    </div>
    <div class="main">
        <fieldset class="clearfix">
            <div class="col-item">
                <label>Nome</label>
                <input type="text" name="Movie[name]" class="text" value="<?php echo $movie->name ?>" data-url-check="<?php echo $this->createAbsoluteUrl('/movies/checkslug') ?>" data-id="<?php echo $movie->id ?>" />
                <span class="key"><?php echo $movie->slug ?></span>
                <input type="hidden" name="Movie[slug]" value="<?php echo $movie->slug ?>">
            </div>
            <div class="col-item single no-space">
                <label>Nome original</label>
                <input type="text" name="Movie[original_name]" class="text medium" value="<?php echo $movie->original_name ?>" />
                <input type="text" name="Movie[year]" class="text small" value="<?php echo $movie->year ?>" placeholder="Ano" />
            </div>
        </fieldset>
        <fieldset class="clearfix file-in-form">
            <label>Poster</label>
            <a href="#" class="pure-button" rel="clickFile" data-origin="normal-button" data-default-text="Enviar Poster">Enviar Poster</a>
            <?php if ($movie->poster): ?>
                <a href="<?php echo Yii::app()->params['aws']['s3BaseUrl'] . $movie->poster ?>" class="pure-button pure-button-secondary" rel="external">Ver Poster</a>
            <?php endif ?>
            <input type="hidden" name="Movie[poster]" value="<?php echo $movie->poster ?>">
        </fieldset>
        <fieldset>
            <div class="col-item small">
                <label>Estréia</label>
                <input type="text" name="Movie[release]" class="text datepicker" data-value="<?php echo $this->dateFormat($movie->release, 'y-MM-dd') ?>" placeholder="Escolha">
            </div>
            <div class="col-item small">
                <label>Duração</label>
                <input type="text" name="Movie[time]" class="text" value="<?php echo $movie->time ?>" placeholder="Ex: 90">
            </div>
            <div class="col-item small no-space">
                <label>Faixa Etária</label>
                <input type="text" name="Movie[age]" class="text" value="<?php echo $movie->age ?>" placeholder="Ex: 12">
            </div>
        </fieldset>
        <fieldset>
            <div class="col-item">
                <label>Gênero</label>
                <?php $this->widget('application.widgets.Tags', array(
                        'fieldName'=>'MovieGenre', 
                        'items'=>$genres, 
                        'selectedItems'=>$movie->genres, 
                        'itemField'=>'name',
                        'htmlOptions'=>array('class'=>'text input-tags', 'autoComplete'=>'off', 'placeholder'=>'Digite o gênero'),
                    )
                ); ?>
            </div>
            <div class="col-item single no-space">
                <label>País</label>
                <?php $this->widget('application.widgets.Tags', array(
                        'fieldName'=>'MovieCountry', 
                        'items'=>$countries, 
                        'selectedItems'=>$movie->countries, 
                        'itemField'=>'name',
                        'htmlOptions'=>array('class'=>'text input-tags', 'autoComplete'=>'off', 'placeholder'=>'Digite o país'),
                    )
                ); ?>
            </div>
        </fieldset>
        <fieldset>
            <div class="col-item">
                <label>Direção</label>
                <?php $this->widget('application.widgets.Tags', array(
                        'fieldName'=>'MovieCast[director]', 
                        'items'=>$directors, 
                        'selectedItems'=>$movie->directors, 
                        'itemField'=>'cast',
                        'itemFieldChildren'=>'name',
                        'htmlOptions'=>array('class'=>'text input-tags', 'autoComplete'=>'off', 'placeholder'=>'Digite o nome do diretor'),
                    )
                ); ?>
            </div>
            <div class="col-item single no-space">
                <label>Atores</label>
                <?php $this->widget('application.widgets.Tags', array(
                        'fieldName'=>'MovieCast[actor]', 
                        'items'=>$actors, 
                        'selectedItems'=>$movie->actors, 
                        'itemField'=>'cast',
                        'itemFieldChildren'=>'name',
                        'htmlOptions'=>array('class'=>'text input-tags', 'autoComplete'=>'off', 'placeholder'=>'Digite o nome do ator/atriz'),
                    )
                ); ?>
            </div>                
        </fieldset>
        <fieldset>
            <label>Sinopse</label>
            <textarea name="Movie[review]"><?php echo $movie->review ?></textarea>
        </fieldset>
        <fieldset class="clearfix review_status">
            <label><input type="radio" name="Movie[review_status]" value="0" <?php if($movie->review_status==0): ?>checked<?php endif; ?>> Não revisada</label>
            <label><input type="radio" name="Movie[review_status]" value="1" <?php if($movie->review_status==1): ?>checked<?php endif; ?>> Revisada</label>
        </fieldset>

        <div class="poster-box">
            <?php if ($movie->poster): ?>
                <img src="<?php echo Yii::app()->params['aws']['s3BaseUrl'] . $movie->poster ?>" alt="">
            <?php endif ?>
            <a href="#" class="pure-button" rel="clickFile" data-default-text="Enviar Poster">Enviar Poster</a>
            <input type="file" class="submitFile hidden" data-show-thumb="true" data-upload-url="<?php echo $this->createAbsoluteUrl('/movies/upload') ?>">
        </div>
    </div>
</form>

<script>
    plugins();
    poster();
</script>

protected/views/movies/index.php
<div id="nav" class="pure-u hidden-mobile">
    <a href="#" class="alternate hidden-desktop">&#9776;</a>

    <ul class="unstyled">
        <li>
            <a href="<?php echo $this->createUrl('/movies/detail') ?>" class="pure-button pure-button-secondary pure-button-small" data-link-ajax="true" data-target="content">Adicionar Filme</a>
        </li>
        <li class="interval"></li>
        <li>
            <a href="<?php echo $this->createUrl('/movies') ?>" class="default active">Filmes</a>
        </li>
        <li>
            <a href="<?php echo $this->createUrl('/cast') ?>" class="default">Atores e Diretores</a>
        </li>
        <li>
            <a href="<?php echo $this->createUrl('/genres') ?>" class="default">Gêneros</a>
        </li>
        <li class="interval"></li>
        <li>
            <label>Filtro</label>

            <form action="<?php echo $this->createUrl('/movies/list') ?>" action="get" name="movieFilter">
                <ul class="unstyled">
                    <li><input type="text" class="text" placeholder="Buscar filme" name="term"></li>
                    <li><label><input type="checkbox" name="filter[]" value="no-poster"/> Sem poster</label></li>
                    <li><label><input type="checkbox" name="filter[]" value="incomplete"/> Incompletos</label></li>
                    <li><label><input type="checkbox" name="filter[]" value="awaiting-approval"/> Aguardando aprovação</label></li>
                </ul>
            </form>
        </li>
    </ul>
</div>
<div id="list" class="pure-u" data-action="<?php echo $this->createUrl('/movies/list') ?>" data-page="2">
    <ul class="unstyled">
        <?php $this->renderPartial('list', array('movies'=>$movies)) ?>
    </ul>
    <a href="#" class="load-more hidden-desktop" rel="more">Carregar mais</a>
</div>
<div id="content" class="pure-u hidden-mobile" data-container="content">
</div>

protected/views/movies/item-list.php
<li class="clearfix <?php echo $movie->itemStatus ?>" id="movie-<?php echo $movie->id ?>">
    <a href="<?php echo $this->createUrl('/movies/detail/'.$movie->id) ?>" class="overlay" data-ajax="true"></a>
    <span class="image">
    	<?php if ($movie->poster): ?>
			<img src="<?php echo Yii::app()->params['aws']['s3BaseUrl'] . $this->getImage($movie->poster, 'small') ?>" width="50">
    	<?php endif ?>
    </span>
    <span class="info">
        <p class="ttl"><?php echo $movie->name ?></p>
        <p class="subttl"><?php echo $movie->original_name ?></p>
        <p class="subttl">Direção: Jorge de Paula</p>
        <p class="obs">
            <?php if ($movie->itemStatus=='incomplete'): ?>
            Incompleto
            <?php elseif($movie->itemStatus=='publish'): ?>
            Aguardando publicação
            <?php endif ?>
        </p>
    </span>
</li>

protected/views/movies/list.php
<?php foreach ($movies as $movie): ?>
<?php $this->renderPartial('item-list', array('movie'=>$movie)) ?>
<?php endforeach ?>
<?php if (!$movies): ?>
<li class="nothing">Nenhum filme encontrado</li>
<?php endif ?>